### ISSUE TITLE
More traits for more units

### ISSUE THREAD

**Issue by cooljeanius** [cooljeanius/Son_Of_The_Black_Eye_Easy_Edition#8]
This is a follow-up to bug #7. Other candidates for gaining more traits (at least on `EASY`): Jetto, Al'Brock, Flar'Tar, Plonk, Inarix

**Comment by cooljeanius** [comment]
@knyghtmare any suggestions for what traits might make sense here?

**Comment by brirush84** [comment]
I think that traits that improve gameplay are better than 'story-appropriate' traits. In particular, I think:

-Kapoue could use quick (to manuever around better for leadership) and strong (to help both with leveling up and after)

-Inarix and the slayers are already fast, but they could definitely use 'resilient, since they're all really squishy. Inarix could benefit from strong due to having 4 strikes, but it's not as useful for the slayers, who really don't benefit from anything.

-Generals don't do much, and we don't really want them moving around, so maybe strong and resilient?

So my vote is for:
-Kapoue strong, quick
-generals strong, resilient
-Inarix strong, resilient
-assassins resilient, ?

Just my thoughts, I think their are a ton of options but this might give you ideas

**Comment by cooljeanius** [comment]
I think I'm going to keep Kapou'e the same, since I already did a playthru with his current traits and they worked perfectly fine for me, but the others are all good suggestions.

**Comment by cooljeanius** [comment]
also the assassins already both have loyal, so just adding resilient will be enough

**Comment by cooljeanius** [comment]
oh and also I think it's perfectly okay to give traits usually reserved for other races to story characters, so dextrous and healthy are on the table here, too, despite being usually reserved for elves and dwarves respectively... in fact, I think dextrous might just make sense as an additional trait for Jetto (not Plonk though)...

**Comment by cooljeanius** [comment]
done in eab8f17
